package tk.graalogosh.ppos.dao.specifications;

import org.apache.commons.lang3.StringUtils;
import org.springframework.data.jpa.domain.Specification;
import tk.graalogosh.ppos.models.Employee;
import tk.graalogosh.ppos.models.Employee_; //generated by Hibernate Metamodel Generator
import tk.graalogosh.ppos.models.Faculty;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by graal on 17.09.2015.
 */
public class EmployeeSpecifications {
    public static Specification<Employee> IDIs(Integer employeeID) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.employeeID), employeeID);
    }

    public static Specification<Employee> nameIs(String name) {
        return (root, query, cb) -> cb.like(root.get(Employee_.name), "%" + name + "%");
    }

    public static Specification<Employee> accessLevelIs(Integer accessLevel) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.accessLevel), accessLevel);
    }

    public static Specification<Employee> registrationDateIs(LocalDate date) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.registrationDate), date);
    }

    public static Specification<Employee> lastLoginDateIs(LocalDate date) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.lastLoginDate), date);

    }

    public static Specification<Employee> isDismissed(Boolean dismissed) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.dismissed), dismissed);
    }

    public static Specification<Employee> facultyIs(Faculty faculty) {
        return (root, query, cb) -> cb.equal(root.get(Employee_.faculty), faculty);
    }
}
